sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t marjook/docker_react -f Dockerfile.dev .

#script:
  #- docker run -e CI=true marjook/docker_react npm run test
after_success:
  - docker build -t marjook/testdockerhub .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push marjook/testdockerhub