sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t marjook/docker_react -f Dockerfile.dev .

script:
  - docker run -e CI=true marjook/docker_react npm run test